#!/bin/sh

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    hdmimode=*) export mode=${arg#*=} ;;
    scaling_governor=*) scaling_governor="${arg#*=}" ;;
    scaling_min_freq=*) scaling_min_freq="${arg#*=}" ;;
    scaling_max_freq=*) scaling_max_freq="${arg#*=}" ;;
  esac
done

HPD_STATE=/sys/class/amhdmitx/amhdmitx0/hpd_state
DISP_CAP=/sys/class/amhdmitx/amhdmitx0/disp_cap
DISP_MODE=/sys/class/display/mode

echo $mode > $DISP_MODE

common_display_setup() {
  M="0 0 $(($X - 1)) $(($Y - 1))"
  Y_VIRT=$(($Y * 2))
  fbset -fb /dev/fb0 -g $X $Y $X $Y_VIRT 32
  fbset -fb /dev/fb1 -g 32 32 32 32 32
  echo $mode > /sys/class/display/mode
  echo 0 > /sys/class/graphics/fb0/free_scale
  echo 1 > /sys/class/graphics/fb0/freescale_mode
  echo $M > /sys/class/graphics/fb0/free_scale_axis
  echo $M > /sys/class/graphics/fb0/window_axis
  echo 0 > /sys/class/graphics/fb1/free_scale
}

case $mode in
  480*)            export X=720  Y=480  ;;
  576*)            export X=720  Y=576  ;;
  720p*)           export X=1280 Y=720  ;;
  1080*)           export X=1920 Y=1080 ;;
  2160p*)          export X=3840 Y=2160 ;;
  smpte24hz*)      export X=3840 Y=2160 ;;
esac

common_display_setup

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Console unblack
echo 0 > /sys/class/graphics/fb0/blank
echo 0 > /sys/class/graphics/fb1/blank

# Boot with performance governor, then switch to the governor specified in the kernel command line
for cpufreq in /sys/devices/system/cpu/cpu[0-9]*/cpufreq; do
  if [ -n "$scaling_governor" ]; then
    echo "$scaling_governor" > "$cpufreq/scaling_governor"
  fi
  if [ -n "$scaling_min_freq" ]; then
    echo "$scaling_min_freq" > "$cpufreq/scaling_min_freq"
  fi
  if [ -n "$scaling_max_freq" ]; then
    echo "$scaling_max_freq" > "$cpufreq/scaling_max_freq"
  fi
done
